/**
 * 全局错误码注册表：前后端统一引用。
 *
 * 边界：
 * - 不负责：异常抛出逻辑（由 BusinessException 处理）
 */

export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  PROMPT_NOT_FOUND: 'PROMPT_NOT_FOUND',
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  SITE_DOMAIN_EXISTS: 'SITE_DOMAIN_EXISTS',
  REVIEW_NOT_PENDING: 'REVIEW_NOT_PENDING',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  LAST_ADMIN_REQUIRED: 'LAST_ADMIN_REQUIRED',
  KEYWORD_NOT_FOUND: 'KEYWORD_NOT_FOUND',
  KEYWORD_EXISTS: 'KEYWORD_EXISTS',
  KEYWORD_CLUSTER_NOT_FOUND: 'KEYWORD_CLUSTER_NOT_FOUND',
  KEYWORD_CLUSTER_EXISTS: 'KEYWORD_CLUSTER_EXISTS',
  GSC_NOT_CONFIGURED: 'GSC_NOT_CONFIGURED',
  GSC_NOT_CONNECTED: 'GSC_NOT_CONNECTED',
  CMS_NOT_CONFIGURED: 'CMS_NOT_CONFIGURED',
  CMS_PUBLISH_FAILED: 'CMS_PUBLISH_FAILED',
  JOB_NOT_PUBLISHABLE: 'JOB_NOT_PUBLISHABLE',
  DRAFT_NOT_EDITABLE: 'DRAFT_NOT_EDITABLE',
  DRAFT_VERSION_CONFLICT: 'DRAFT_VERSION_CONFLICT',
  DRAFT_EXPORT_STALE: 'DRAFT_EXPORT_STALE',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  LLM_PARSE_ERROR: 'LLM_PARSE_ERROR',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
